production:
  mysql41: 9312
  bin_path: '/usr/bin'
  log: "log/searchd.log"
  query_log: "log/searchd.query.log"
  pid_file: "log/searchd.pid"
  mem_limit: 64M
  morphology: stem_enru
  enable_star: true
  min_infix_len: 3
  max_matches: 1000
