production:
  mysql41: 9312
  #bin_path: '/usr/bin'
  log: "logs/searchd.log"
  query_log: "logs/searchd.query.log"
  pid_file: "logs/searchd.pid"
  mem_limit: 64M
  morphology: stem_enru
  enable_star: true
  min_infix_len: 3
  max_matches: 1000
  utf8: true
